### ISSUE TITLE
Checking if records exists on all nameservers

### ISSUE THREAD

**Issue by Svolentin** [Gandi/dnsknife#6]
hi. 
how I can check if TXT records installed and synchronised on all nameservers? 
```Checker('example.com', direct=True).has_txt('dbef8938bef', ignore_case=True)``` checks random/first nameserver and if found - it return True, else False.
but nameservers can be in unsynchronised state about few minutes, so may be this is missing functionality?

**Comment by kalou** [comment]
There's something to do on checks wrt NS consistency, agreed - plus we use it for CDS today.

- sometimes you'll consider one random NS query authoritative (for ex. A on a name - a fast single lookup is ok)
- sometimes you're happy if ANY NS has the info -- ie retry until found (for ex. DNS challenge and slow provisioning/slaves ?)
- sometimes you want to ensure ALL NS are consistent (CDS is one of those, for example).

**Comment by kalou** [comment]
This has been taken care of in commit 7f1415bd394b26f36807e003caa715119643cfe1
